### ISSUE TITLE
Improve the search feature

### ISSUE THREAD

**Issue by abhi211199** [AASF-IIITM/ExpenseCalculator#1]
### The search box in navbar searches for expenses added by user.
![Screenshot from 2020-09-29 01-20-29](https://user-images.githubusercontent.com/36303692/94479279-32260d00-01f2-11eb-9fa2-d8ff399c8c6d.png)
Due to a logical error, the search query is compared with contents of whole page, while, it should have been compared with only the `Expense Name` field. 
*For eg: searching for `mo` should only show up the 2nd expense, but currently it shows both the expenses due to match between **`mo`** and Expense A**mo**unt*

### Fix the error!

**Comment by varunks99** [comment]
@manishdangi98, I'd like to take this up if it is open.

**Comment by Shikhar15606** [comment]
@manishdangi98 Sir I am from IIIT Gwalior
Can I take this

**Comment by abhi211199** [comment]
@Shikhar15606 please go forward with the issue!
