### ISSUE TITLE
Convert time to different format

### ISSUE THREAD

**Issue by abhi211199** [AASF-IIITM/ExpenseCalculator#3]
### Display the date in the form of `Month Day, Year(for eg: Sep 20, 2020)`
![Screenshot from 2020-09-29 01-30-23](https://user-images.githubusercontent.com/36303692/94480643-3bb07480-01f4-11eb-93b3-04da0834d423.png)

**Comment by pronayguha13** [comment]
Hey I'm up for it...
Looks to be interesting

**Comment by mohammed786** [comment]
Hey @abhi211199 ,

I would like to work on it.

**Comment by codeslash21** [comment]
Hii @abhi211199 
I will take this issue if its no problem.

**Comment by manishdangi98** [comment]
> Hey @abhi211199 ,
> 
> I would like to work on it.

Hey, @mohammed786  Glad, you want to contribute but I'm really sorry to inform you that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by manishdangi98** [comment]
> Hii @abhi211199
> I will take this issue if its no problem.

Hey, @codeslash21 Glad, you want to contribute but I'm really sorry to inform you that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by Swarnim01** [comment]
@abhi211199 @manishdangi98 sir.....i would like to work on this issue

**Comment by abhi211199** [comment]
@Swarnim01 assigned to you!

**Comment by Swarnim01** [comment]
@abhi211199  i changed the format and added seperate field for date and time..If you appprove...i'll go forward with it
![2020-10-01 (2)](https://user-images.githubusercontent.com/56025388/94794368-5ef84100-03f9-11eb-8eac-075ca31ed8b9.png)
